[project]
name = "fastapi-app-template"
version = "0.1.4"
description = "Template for FastAPI project"
readme = "README.md"
requires-python = ">=3.12.7"
dependencies = [
    "fastapi[standart]>=0.115.5",
    "httpx>=0.27.2",
    "pydantic-settings>=2.6.1",
    "pyjwt>=2.10.0",
    "pytz>=2024.2",
    "sqlalchemy[postgresql-asyncpg]>=2.0.36",
    "uvicorn>=0.32.1",
]
